### ISSUE TITLE
[Bug] When a factoid is called in the wrong case, a blank factoid is created

### ISSUE THREAD

**Issue by Southpaw1496** [LordRalex/absol#14]
For example, called `Test` instead of `test` will return the message shown below:
![Screenshot 2020-10-10 at 11 58 02 am](https://user-images.githubusercontent.com/44805409/95653330-db70db00-0aef-11eb-8155-7ecff388e1be.png)

Let me know if any more information is required.

**Comment by randomairborne** [comment]
this was fixed, shouldn't it be closed?

**Comment by Southpaw1496** [comment]
I was unaware that it had been fixed, yes, it should.
